### ISSUE TITLE
need official Vagrant docs

### ISSUE THREAD

**Issue by aspiers** [openSUSE/kiwi#394]
As mentioned in #390, the [official kiwi documentation](http://doc.opensuse.org/projects/kiwi/doc/) does not mention Vagrant at all.  I guess there was a reason for [documenting the Vagrant stuff in the wiki instead](https://github.com/openSUSE/kiwi/wiki/Building-vagrant-boxes) but ideally it should eventually become part of the official docs.

**Comment by schaefi** [comment]
done now

http://doc.opensuse.org/projects/kiwi/doc/#chap.vagrant
