### ISSUE TITLE
zerofree-like approach for Vagrant boxes

### ISSUE THREAD

**Issue by aspiers** [openSUSE/kiwi#404]
I see that [kiwi uses the standard `dd if=/dev/zero && rm` trick](https://github.com/openSUSE/kiwi/blob/92ed69c5487d489f502858a7984c93f60a106965/modules/KIWIBoot.pm#L2675), presumably to aid compression of the generated images.  This is cool, but AFAICS has two issues:

* It doesn't seem to happen for Vagrant box builds (at least, I can't see the `Filling target device with zero bytes...` message anywhere in [the build log](https://build.suse.de/build/Devel:Cloud:4:Vagrant/boxes/x86_64/suse-cloud-vagrant-admin/_log)).
* [It destroys the sparseness of the image.](http://intgat.tigress.co.uk/rmy/uml/index.html)  It would be awesome if we could harness the [`zerofree` utility](http://intgat.tigress.co.uk/rmy/uml/index.html) in `ext2` cases (I guess it probably works for `ext3` too, and maybe even `ext4`.)

**Comment by schaefi** [comment]
finally I found time to work on this one.

I make use of zerofree now and deleted the "old" way. I also have tested how much we gained with the old approach on xfs and btrfs and it was not really a big difference in the file size. zerofree only works for extX based filesystems but there the compression differences are recognizeable and the free blocks scan is much faster than creating a big zero junk. The kiwi output should now mention something like

```
Scanning ext3 free blocks and replace them by zero...
```

or if we don't have a tool which does that for us

```
No free blocks analyzer available for $blktype
```

with blktype = TYPE value of blkid for this image

All this in #1cc61d192375575975a4bc3a12f4fec4ab46018a

**Comment by aspiers** [comment]
Excellent, thanks!  I think in some cases it could make a big difference, e.g. if the `config.xml` causes deletion of a large number of files, and as you say the free blocks scan is faster too.

BTW it is nice to take advantage of [github's auto-closing feature](https://help.github.com/articles/closing-issues-via-commit-messages/) because then the commit message and the issue it fixes automatically get linked to each other which is very useful for future reference.

**Comment by schaefi** [comment]
>    BTW it is nice to take advantage of [1]github's auto-closing feature
>    because then the commit message and the issue it fixes automatically
>    get linked to each other which is very useful for future reference.

right, thanks for pointing that out, hope I remember to add it to the
commit message before I push :)
