### ISSUE TITLE
Vagrant + kiwi -> do not find obs://repos ?

### ISSUE THREAD

**Issue by T1loc** [openSUSE/kiwi#426]
I got this following message : 

  125s] + /usr/bin/yum '--disablerepo=*' -c /var/cache/kiwi/yum/yum.conf -y --installroot=/usr/src/packages/KIWIROOT-vmx install basesystem filesystem glibc yum
[  125s] Setting up Install Process
[  125s] No package basesystem available.
[  125s] No package filesystem available.
[  125s] No package glibc available.
[  125s] No package yum available.
[  125s] Error: Nothing to do

I paste my log file : 
http://susepaste.org/58052970

I don't know how to fix this problem

**Comment by schaefi** [comment]
the repo setup seems broken or building centos images with yum inside of a buildservice environment is not supported. For now I would say we should eliminate some parts of the equation. The patch with disablerepo=* disables all repos also the ones kiwi added for building images. That broke it :)

I reverted the patch and tested a rhel build (sorry I don't have centos at hand) as follows:

```
make
sudo make install

sudo bash
kiwi --prepare rhel-06.0-JeOS --root /tmp/mytest-rhel
```

This works for me:

+ /usr/bin/yum -c /var/cache/kiwi/yum/yum.conf -y --installroot=/tmp/mytest-bob install basesystem filesystem gfxboot-branding-upstream redhat-logos yum-plugin-priorities yum
Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package basesystem.noarch 0:10.0-4.el6 will be installed
...

According to that I suggest you test kiwi image building locally first and if everything works as you want it you should go to the buildservice. You can find the rhel template I have used in the git here

template/ix86/rhel-06.0-JeOS/

**Comment by T1loc** [comment]
Perhaps we can pass this option : enablerepo with all the repo in config.xml ?

**Comment by T1loc** [comment]
or (my first idea on irc,) remove all repo file in /etc/yum.repos.d/*.repo

**Comment by T1loc** [comment]
And If I try your commands (kiwi --prepare ...) It's works with my own config.xml

**Comment by schaefi** [comment]
glad to hear that it worked for you on the commandline

you suggested to remove  "/etc/yum.repos.d/*.repo". I'm not sure if we should do that think of people using yum for managing the host system. I think they will kill us :)

kiwi creates the repos for the image building task below /var/cache/kiwi/yum/... 
kiwi also creates a yum.conf including among other things:

reposdir=/var/cache/kiwi/yum

I'm wondering why the default repo path is still in use ? Are you sure the repos in /etc/yum.repos.d/
are really used ?

**Comment by schaefi** [comment]
maybe your problem is that /var/cache/kiwi/yum/ contains repos from other image build attempts
you can try rm -rf /var/cache/kiwi/yum and retest again

actually there should be no waste in there but if kiwi was e.g killed or some other problem caused it to become killed before the cleanup could do its job this problem could come up

**Comment by T1loc** [comment]
Actually I'm not sure, but when a do a @yum repolist -> launch manually with kiwi, all my repo are correctly setup, but with the obs I got only the installed packages.

I try to debug with my own obs instance, and actually I don't understand why the repo file in /var/cache/kiwi/yum/*.repo are almost empty

Eg: 
filename : appliance.repo
file content : [appliance]

Same thing with yum.conf -> only [main]

Perhaps we can close this issues, I will investigate much as I can.

**Comment by schaefi** [comment]
ok, I think its more targeted to the buildservice. maybe Adrian Schröter can help
