### ISSUE TITLE
Build SLES11 SP1 images with zypper 1.3.21 without --pkg-cache-dir

### ISSUE THREAD

**Issue by jarus** [openSUSE/kiwi#470]
Hi,

I would like to build a SLES11 SP1 with KIWI 7.02.55 but KIWI tries to use the ``--pkg-cache-dir`` option of zypper which isn't available in the "newest" zypper version included by SLES11 SP1 (1.3.21).

```bash
+ chroot /tmp/sles11-sp1-root zypper --non-interactive --pkg-cache-dir /var/cache/kiwi/packages --reposd-dir /var/cache/kiwi/zypper/repos --solv-cache-dir /var/cache/kiwi/zypper/solv --cache-dir /var/cache/kiwi/zypper --config /var/cache/kiwi/zypper/zypper.conf.6 --no-gpg-checks install --auto-agree-with-licenses --no-recommends coreutils iputils
Unknown option '--pkg-cache-dir'
``` 

Regards
Christoph

**Comment by schaefi** [comment]
if you have to build sles11 sp1 you can do that by putting all packages into the 

```
<packages type="bootstrap"/>
```

section. This causes that only the build host zypper is used to install the image root.
That workarounds the zypper version problem for sp1

sles11 is currently at sp3 which has a compatible zypper version and sp4 will be out end of June
