### ISSUE TITLE
A tool is needed to compatibly put isohybrid images on sticks without wasting space

### ISSUE THREAD

**Issue by v-fox** [openSUSE/kiwi#475]
A proper way (the one that allows to use it for advanced Linux booting and file sharing with random legacy systems) to create a boot sticks with 2 partitions, one for an OS and one for redundant space, is:
1) Calculate the amount of the redundant space ({total space} minus {space that's needed for OS}).
2) Allocate that space and create a fat partition, so stupid Windows® systems could see it (because it only looks for the first partition and in its pathetic filesystems). It's not really have to be first, only it's partition number should be and it [can be done manually](http://unix.stackexchange.com/questions/18752/change-the-number-of-the-partition-from-sda1-to-sda2). I think at least one of Linux msdos partitioning tools (cf/f/s/disk, parted, etc.) allows that but it was too long ago since I did such.
3) Allocate that space, create and prepare proper partition for an OS image.
Or, I suppose, one can imitate with Grub or SysLinux what's [IsoStick](https://isostick.com) is doing. But that's overcomplicated, unreliable and has too much limitations (like a size below 4GB).

I noticed that kiwi has something called `livestick` and there is also [these scripts](https://en.opensuse.org/SDB:Live_USB_stick#Using_live-fat-stick_.28Command_line_or_GUI_way.29)  but they are [doing it wrong](https://github.com/cyberorg/live-fat-stick/issues/18).

**Comment by schaefi** [comment]
You are saying livestick did not work for you ? I have tested it today and also made it more robust in terms of device detection (now based on uuid instead of by-id) and it worked good for me

I wrote the following article how to use it:

https://github.com/openSUSE/kiwi/wiki/Create-live-system-from-data-stick

Let me know if that works for you

**Comment by v-fox** [comment]
I don't say "it didn't work", i would say that it's an undocumented thing of unknown purpose that I'm afraid of launching. There is 2 approaches of making a bootable stick that I know: one is described above and chainloading through GRUB or SysLinux. And the latter is more like a software imitation of what [IODD/Zalman SATA boxes](http://www.ixbt.com/storage/esata-p22-zalman.shtml) (for some reason all English mentions of them have disappeared from [Zalman site](http://www.zalman.ru/global/product/product_read.php?id=186) and IODD site is down) are doing. I really would like have an automated way of doing it by the first approach, avoiding chainloading and FAT.

Kiwi has 'persistency' option that allows automatic creation of ext2 partition for R/W support, I basically want that but for FAT and without R/W support... or both FAT and ext2 partitions for both. Kiwi also has '--fat-storage' option but it's not automatic in size selection and doesn't seem to be aimed for iso building.

**Comment by schaefi** [comment]
>  i would say that it's an undocumented thing of unknown purpose 

agreed and fixed by the wiki article now :)

> I really would like have an automated way of doing it by the first approach, avoiding chainloading and FAT.

ok iirc that would mean we extend the livestick script in a way that does the creation of the second partition and use that as the OS rootfs to boot from, correct ?

I just have seen Windows machines which doesn't like if a stick contains multiple partitions even if the first one contains a fat filesystem. Do you have reasons why the way livestick sets up the stick at the moment is not appropriate for your use case ? maybe performance, or fixed cowfile size, etc... ?

Thanks

**Comment by v-fox** [comment]
> agreed and fixed by the wiki article now :)

Cool ! But, please, add a man page or verbose help output for the binary. Today I actually found its existence slightly before you've mentioned it... but I failed to discern it purpose and workings before you stated it here.

> ok iirc that would mean we extend the livestick script in a way that does the creation of the second partition and use that as the OS rootfs to boot from, correct ?

It may be done so or you can extend the firstboot script of the kiwi's initrd instead. The one that creates ext2 partition for persistency. Imagine if when "hybridpersistent" option was set the firstboot script would launch a timeout (like 30s) while asking user to input how many percents (with zero by default, maybe) of available redundant space (exact amount of which would be handy to show) he would like to allocate for "Windows®-compatible partition" or such. The rest will be ext2 for R/W. Then script would make those 2 partitions and assign number "1" for the FAT one.
In case of non-persistent build that would be "100%" by default without an option to change and with RAM for R/W. Or maybe even so that persistency would be decided entirely on the first boot (if user has set 100% or not) and not before the build.

> I just have seen Windows machines which doesn't like if a stick contains multiple partitions even if the first one contains a fat filesystem.

Mmm... that warrants investigation. Do they not mount those partitions or what ? Maybe just "fstype" problem or something ?
I've seen machines with BIOS'es that were picky on wanting to boot syslinux and grub sticks. Mostly because they didn't like MBR on them for some reason or were doing something weird with EFI. This is why I prefer the hardware solution for choosing between multiple live distros. But even that has its limitations since their image-finding logic is based on Microsoft® FSs. The biggest problem there, on IODD enclosures, is with fragmentation. But in case of [IsoStick](https://isostick.com/) it's more of a mixed solution. I've heard that for making boot selection menu (which IODD devices have right on them along the multi-purpose selection switch) IsoStick guys are feeding some bootcode to BIOS'es which some of them don't like.

And I would really like to avoid any unnecessary bootcode for the sake of reliability. Besides, that just looks like more technically correct solution. And if you add a boot option of "trying to boot a compatibility partition" by chainloading to syslinux of FAT partition the ability to add memtest, multiple isoes, a DOS system, or what have you, still will be available.

**Comment by schaefi** [comment]
> Mmm... that warrants investigation. Do they not mount those partitions or what ? Maybe just " 
> fstype" problem or something ?

Windows refused to "mount" it, there is a way to "mount" the fat part however, but the nice "automatic" inclusing was gone if WIndows detected more than one fat partition on it. Not sure if this is still the case on today's Windows versions

Another problem with partitions is that there might not be enough space left on the device to create one. This is in almost all cases true when people just use a pre formatted (vfat) stick they just bought from somewhere. Technically it would be required to shrink the existing partition. There are tools which could do that but the operation is never save and the risk to loose the data already stored on the device is high. Whenever I do that I create a backup of the data first :)

This is also one of the reasons why kiwi's livestick script creates just a cow file without messing with
the underlaying partition or filesystem layer

**Comment by v-fox** [comment]
> Windows refused to "mount" it, there is a way to "mount" the fat part however, but the nice "automatic" inclusion was gone if WIndows detected more than one partition with an unknown filesystem signature Not sure if this is still the case on today's Windows versions

I only seen this for non-first partitions. Maybe you just forgot to put "type" for those since Windows can't actually detect fs types itself, unlike Linux ?

> Another problem with partitions is that there might not be enough space left on the device to create one. This is in almost all cases true when people just use a pre formatted (vfat) stick they just bought from somewhere. Technically it would be required to shrink the existing partition. There are tools which could do that but the operation is never save and the risk to loose the data already stored on the device is high. Whenever I do that I create a backup of the data first :)

Oh, come ooon, we talking about putting giant bootable systems with hybrid booting on sticks which I always do by pure `dd`, why would you want to "preserve" data unless you just updating your image ? Just nuke the damn thing, partitions and their table, everything !
However, it brings up 2 problems with my idea:
1) Before making new partitions it would be wise to check if it was already partitioned by kiwi system and let things be they way they are.
2) On update new image may be larger than the previous one, which means that a part from ext2 partition should be cut off to compensate or partition with squash/overlay should be made 10-20% larger than required.

But that's quite overcomplicated in comparison to just making ext2+vfat partitions instead of pure ext2. Or people should just make backups when they put giant multi-purpose live system on their sticks like I do.

**Comment by schaefi** [comment]
> Oh, come ooon, we talking about putting giant bootable systems with hybrid booting on sticks    
> always do by pure dd, why would you want to "preserve" data unless you just updating your image ? > Just nuke the damn thing, partitions and their table, everything !

Ha Ha, who cares for data :) I see the point and yes that makes it a lot easier, however the use case that people want to use a stick as data container and as a system for the rescue without loosing data is a pretty important one.

I'm totally ok with not taking care for it in this scenario ;)

**Comment by schaefi** [comment]
Im going to test a patch remembering you said only  the Partition number of the fat needs to be the First one but the real address could be elsewere. Windows does only look up the number is this correct ?

**Comment by v-fox** [comment]
> Im going to test a patch remembering you said only the Partition number of the fat needs to be the First one but the real address could be elsewere. Windows does only look up the number is this correct ?

At least this is how I always done it because pre-calculating it is hard and unhandy. BUT I just rechecked it, couldn't remember how to just change the number and instead
1) deleted EFI (1) and data FAT (3) partitions
2) added EFI as number 3 and data FAT as number 1 while them really being 1 and 3
3) formatted them
And to my surprise... it failed. The damn thing (Windows 8.1) have mounted EFI partition WHILE showing in its "computer management" -> "disk management" that it mounted data FAT partition. Look at this !
![w8 1 mount fail](https://cloud.githubusercontent.com/assets/362763/8854087/950a7290-3177-11e5-89f1-b9245b1fe2a7.png)
I don't rememeber something like this happening without EFI partitions... And look at this, in thing called [MiniTool Partition Wizard](http://www.minitool.com/partition-manager/partition-wizard-home.html):
![w8 1 mount fail - mtpw perspective](https://cloud.githubusercontent.com/assets/362763/8854537/c4477fec-3179-11e5-8e5b-5ad765977550.png)
The same drive looks different in different tools under WIndows >_< It completely confused by what kiwi does. It thinks that EFi partition is at the beginning and the end of live cd partition at the same time !

Then I "deleted" the phantom EFI partition that it so keen on mounting, tried to "create" a new one at the end which should be there in the first place MTPW said:
![w8 1 mount fail - mtpw mkfs](https://cloud.githubusercontent.com/assets/362763/8854673/912c9fa6-317a-11e5-8899-3915e3d43fd4.png)
... and then it tried to format it, hanged for an entire minute.. and then Windows gone completely damn nuts, I wish I've made a video of that shit -_- In the list of "disk management" it started showing and hiding every second 2 phantom EFI partitions at the end of the livecd one and after about 5-10 seconds it decided that those 2 partitions are real... without showing them on the bottom. I formated it again, now from "disk management" and it showed that it mounted it... but it lied. It showed EFI partition with the name of data FAT partition while not really mounting any of them.

So, it seems that combination of ISO partitioning + msdos partitioning + EFI makes Windows go completely bonkers. Damn.
And this is probably what you were seeing with

> Windows machines which doesn't like if a stick contains multiple partitions even if the first one contains a fat filesystem

**Comment by v-fox** [comment]
However, changing numbers for those partitions shouldn't break it any more than it already is broken and if you could figure out what exactly makes it loose its half-dead mind it may actually work. It always worked on simple syslinux-only images, at least, where are 2 FAT partitions: first one witn number 2 contained squash root & kernel for livecd and is inaccessible for Windows and second has number 1 and is mountable.

But I'm starting to see the point about giving up on this and just having 1 partition for Windows glitch-compliance.

**Comment by schaefi** [comment]
It has some pro and cons to invest time in this one. Basically there is only one part I'm really convinced we should not do, and that's to use a fat or ntfs file system together with the root fs of a linux OS. I have done several tests today and due to missing support for e.g symlinks, large files, extended file attributes and more you are running in a bunch of problems when working with the linux OS

Therefore I have created a patch in kiwi which allows to create a hybrid iso which creates a fat space as first partition (the number is 1, but the address is not the first one). On this fat partition a file is created containing a btrfs filesystem which works pretty fast together with the overlayfs setup to combine the squashfs compressed rootfs from the iso. The size of the btrfs is calucalted as 1/2 of the size of the fat filesystem.

I think that meets many of your requirements

* fat on first partition
* boot via syslinux (isolinux)
* hybrid image
* fat space is not entirely shared with the linux OS, for the reasons I tried to explain above. I think we have to live with this limitation if the first partition has to be a fat or ntfs partition

__How can you create it ?

Here is the type definition

```
<type image="iso" primary="true" boot="isoboot/suse-13.2" flags="overlay" hybrid="true" firmware="bios" kernelcmdline="splash" hybridpersistent_filesystem="fat"/>
```

* You need kiwi >= v7.03.9. I'm going to release that one soon (after CI tests are done)

__How can you test it ?

I have tested with:

qemu-img create mydisk 6g
dd if=LimeJeOS-openSUSE-13.2.x86_64-1.13.2.iso of=mydisk conv=notrunc

qemu-kvm mydisk

On the boot prompt I entered

kiwi_hybridpersistent=true

you can set that also in your XML description, but for debugging it's easier to be able to switch
persistency on and off on the boot prompt

Let me know what you think

**Comment by schaefi** [comment]
I'll re open this one for feedback, would be great if you can give it a test on Windows because I don't have one at my place :)

**Comment by v-fox** [comment]
> It has some pro and cons to invest time in this one. Basically there is only one part I'm really convinced we should not do, and that's to use a fat or ntfs file system together with the root fs of a linux OS.

Oh, that's definitely. fat and ntfs are nothing more than support braces for systems that are barely an OS. Which are too ubiquitous, unfortunately.

> On this fat partition a file is created containing a btrfs filesystem which works pretty fast together with the overlayfs setup to combine the squashfs compressed rootfs from the iso.

I not quite understood:
1) It's a btrfs in a file and not a partition ? Because if that's the case it doesn't seem any different from usual chainloading by syslinux which I'm trying to avoid.
2) Is it compressed ? Because my system is about 2.8GB compressed and ~10GB uncompressed.
3) Or do you mean that this is only for R/W (persistency) support and R/O is done as usual ? Then it seems fine.

>I think that meets many of your requirements

My requirements would be more like:
1) Linux system on its own partition.
2) R/W | persistency support for some of the redundant space.
3) Windows-compatibility for the rest of the redundant space. Preferably in a way that wouldn't let Windows mess with Linux stuff.

That would make a nice reason to get a high-speed USB3 32GB stick.

> You need kiwi >= v7.03.9. I'm going to release that one soon (after CI tests are done)

Great ! I think I will wait for update since I always using kiwi from Virtualization:Appliances repo.

> firmware="bios"

Any change of U/EFI & SB compatibility ? I actually can't test it, maybe only with some VM magic. But I would really like to have it loading out-of-the-box on those pesky "Secure Boot" machines.

> On the boot prompt I entered
> kiwi_hybridpersistent=true

Hah, you can toggle that on boot ? Is there documentation for all kiwi-specific boot options ?

> I'll re open this one for feedback, would be great if you can give it a test on Windows because I don't have one at my place :)

Ouh-yeah, I'll try it out on nearest update, maybe even use it for my livecd's next release.

**Comment by schaefi** [comment]
> I not quite understood:
> 3) Or do you mean that this is only for R/W (persistency) support and R/O is done as usual ? Then it seems fine.

This one was meant

>My requirements would be more like:
>1) Linux system on its own partition.

This is the case, it lives on the second partition, squashfs compressed

>2) R/W | persistency support for some of the redundant space.

This is the case, using an overlayfs based cow file living on the first partition

>3) Windows-compatibility for the rest of the redundant space. Preferably in a way that wouldn't let Windows mess with Linux stuff.

This should be the case with the fat partition which is now the first one. Your Windows should see the cow file though. I haven't tested that and thought you could just try that

> Hah, you can toggle that on boot ? I

Exactly :)

If you have an upload location for me, I also can upload my test iso to your space, 257M

**Comment by v-fox** [comment]
Cool !

> This is the case, using an overlayfs based cow file living on the first partition

But doesn't it mean that file is limited to 4GB ? Which should be plenty for its purpose but still.

> If you have an upload location for me, I also can upload my test iso to your space, 257M

Unfortunately I myself stuck with SourceForge for big files. I've opened write access to you on a folder on my "Google Drive" thought (there should be an email), maybe that would work.

And you haven't answered about EFI and kiwi boot option documentation yet.

**Comment by schaefi** [comment]
yes the 4g limitation exists, however I think if you need more than 4g of pure write space it might be a good idea to rethink the use case of the live system :)

> I've opened write access to you on a folder on my "Google Drive" 

did not receive an e-mail so far

> And you haven't answered about EFI and kiwi boot option documentation yet.

I tried it here: http://doc.opensuse.org/projects/kiwi/doc/#idm139735449627376
btw: we currently work on the kiwi docs, at the end of August there will be a reworked version available on suse.com/documentation

**Comment by schaefi** [comment]
ok I have tested the image on a Windows 8 machine and it has worked nicely. This means if you plugin the stick on a Windows machine you just see content and it does not complain :)

**Comment by v-fox** [comment]
> yes the 4g limitation exists, however I think if you need more than 4g of pure write space it might be a good idea to rethink the use case of the live system :)

The use case is "the ultimate desktop live system, from network analysis to funzies". It would be nice to not think about limitations but as of now I indeed don't know a situation in which they would be hit.

> did not receive an e-mail so far

It seems that GD doesn't send them or something. Doesn't matter now.

> btw: we currently work on the kiwi docs, at the end of August there will be a reworked version available on suse.com/documentation

Great ! I wanted to say for a long time now that kiwi docs could use a rewrite. These are the weirdest docs that I've read, even though they are grammatically correct they still hard to fathom and often bring more questions than answers.

> ok I have tested the image on a Windows 8 machine and it has worked nicely. This means if you plugin the stick on a Windows machine you just see content and it does not complain :)

Windows 8 indeed opens "data" partition fine BUT in my testing on 64G USB3 stick **the RW file was created mere 1MB in size and in ext2 filesystem**, instead of expected btrfs for 4GB. Of course system immediately gone into unusable state with "not enough space on device" errors. That's not right, to say the least.

Also, if you are going to use btrfs, please enable compression by default.
For U/EFI support I would suggest just setting "0xEF" (EFI) type for "data" partition & putting shim-loader there, since Windows is sooo keen on mounting it anyway. That way it would both boot and mount on glitchy firmwares and OSes.

**Comment by v-fox** [comment]
The size & type glitch may have something to do with me using qemu-tools-2.3.91 or its file size being impossible on fat fs.

**Comment by v-fox** [comment]
And on second attempt to boot it tries to make a partition with ID "3" which it obviously fails. And then it gets stuck on an infinite wait for /dev/sdX3. So, it's far from being "closed" yet.

**Comment by schaefi** [comment]
> And naming the file something more explanatory would be useful, like
> Linux_live_system_write_support_image.btrfs".

agreed

> the RW file was created mere 1MB in size and in ext2 filesystem

if this is the case I would say the image you are using was not build with the adaptions we made here
How did you build the image ? In comment https://github.com/openSUSE/kiwi/issues/475#issuecomment-124544634 I provided the details

With efi capable images there is the problem that isohybrid does not respect the --entry option in combination with --uefi. Therefore the write partition is created with a different id (not 1 as we want it)

> So, it's far from being "closed" yet. 

That could be true but involves other tools to move

* 4g limit of fat, I think nobody on earth will ever fix that :)
* --entry support for isohybrid when used with --uefi, that one I have reported to the maintainers

**Comment by v-fox** [comment]
> How did you build the image ?

Like [that](https://github.com/v-fox/live_opensuse_hsf/blob/9152aa337df6a8523a33dc60bc44470d0edae464/config/head)
"kiwi revision: 29fdddecc4d347cd4df2e423c98eab706c83c02f"

> With efi capable images there is the problem that isohybrid does not respect the --entry option in combination with --uefi. Therefore the write partition is created with a different id (not 1 as we want it)

Not quite understand how it works but it seems like an unnecessary limitation on its part. After all, it deals with the same fat.

> 4g limit of fat, I think nobody on earth will ever fix that :)

Well, we can use exfat (in fact, pretty much any fs can be selected for the partition and persistency file). This is why I make exfat-nofuse builds. But I doubt that U/EFI systems would boot from it. Or maybe they will, and it wouldn't make difference for bios-only builds anyway.

**Comment by v-fox** [comment]
Is there any chance that you would look into that in near future ? Because, otherwise, I will have to drop that idea for now and use usual persistency. At least un-close it until it's working.

**Comment by schaefi** [comment]
* I have reported the isohybrid --entry option in combination with --uefi bug to the maintainer

* Regarding exfat I see that it has not really landed in the kernel and is implemented as user space (fuse-exfat) implementation for linux. Because of that I did not adhere to make use of it. Do you have experience in terms of stability ?

**Comment by schaefi** [comment]
So what we are missing is support for exfat in:

```
hybridpersistent_filesystem="exfat"
```

**Comment by v-fox** [comment]
> I have reported the isohybrid --entry option in combination with --uefi bug to the maintainer

Good, I hope soon we may get ourselves truly universal live systems.

> Regarding exfat I see that it has not really landed in the kernel and is implemented as user space (fuse-exfat) implementation for linux. Because of that I did not adhere to make use of it. Do you have experience in terms of stability ?

It will not land with the same reason why in-kernel ntfs support is artificially restricted: fear of extortion in USA-like legal systems through software patenting. BUT out-of-tree kernel implementation of [exfat-nofuse](https://github.com/dorimanx/exfat-nofuse) seems to be up to the task, I [build its modules](https://build.opensuse.org/package/show/home:X0F:HSF/exfat-nofuse) for my live images. The only problem that I had is fragmentation which Zalman/IODD virtual disk drives do not like but that's a part of Microsoft® filesystems' design, doubt that drivers can do anything to alleviate it.
I did not find any difference with [exfat-fuse](https://software.opensuse.org/package/fuse-exfat) beyond horrendous speed and CPU usage which is expected from FUSE implementation. But I didn't use it much, mostly exfat-nofuse.

> So what we are missing is support for exfat in: `hybridpersistent_filesystem="exfat"`

Indeed, exfat fs may be created with `exfat-utils` and then mounted with either fuse or nofuse implementation.

But I even more concerned with previously mentioned:
1) File size glitch.
2) Attempts to create persistency partition after it was already done.

___
Then it's all done, the only thing that may improve it further is encryption option for persistency file but that's a matter of convenience. An encrypted image for sensitive data can be manually created alongside persistency file if user so desires.

**Comment by v-fox** [comment]
In addition to this pull request, here's a patch for `syslinux` that can allow '--entry' option with '--uefi':
```
From 70570adac524a2ef016d3987cc3d807fe65ca74c Mon Sep 17 00:00:00 2001
From: v-fox <virtuousfox@gmail.com>
Date: Mon, 26 Oct 2015 11:31:44 +0500
Subject: [PATCH 2/2] allowing to set partition id entry in U/EFI mode

---
 utils/isohybrid.c | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/utils/isohybrid.c b/utils/isohybrid.c
index d6891c0..ac2d636 100644
--- a/utils/isohybrid.c
+++ b/utils/isohybrid.c
@@ -317,8 +317,8 @@ check_option(int argc, char *argv[])
             entry = strtoul(optarg, &err, 0);
             if (entry < 1 || entry > 4)
                 errx(1, "invalid entry: `%s', 1 <= entry <= 4", optarg);
-	    if (mode & MAC || mode & EFI)
-		errx(1, "setting an entry is unsupported with EFI or Mac");
+	    if (mode & MAC)
+		errx(1, "setting an entry is unsupported with Mac");
             break;
 
         case 'o':
@@ -1023,7 +1023,7 @@ main(int argc, char *argv[])
     if(mode & MAC) part_mac = 3;
 
     if(entry) {
-      if(entry != part_efi && entry != part_mac) part_data = entry;
+      if(entry != part_mac) part_data = entry;
     }
 
     srand(time(NULL) << (getppid() << getpid()));
-- 
2.6.2

```

I also tried to [port openSUSE patch on which kiwi relies](https://build.opensuse.org/package/view_file/home:X0F:HSF/syslinux/0001-openSUSE-specific-EFI-booting-implementation.patch?expand=1) to latest stable and bleeding edge syslinux but despite result looking good, isolinux refused to load.

**Comment by v-fox** [comment]
Can you, please, comment on patch above and the perspective of adding U/EFI support for such mode with it ?

Also, for some reason in my latest test a /cow directory and the loop-file within it are inaccessible from running system, `losetup` lists it as "deleted" and the file is absent on manual mount of its partition... all while system is actually using it ! Which leads me to believe that it for some reason is deleted on switch of the root from initrd's init to the system's init, along with its /cow directory. Do you know how that could happen ?

**Comment by v-fox** [comment]
Oh, goddammit... kiwi decided to nuke all "unnecessary" kernel modules despite me [overriding source/images.sh](https://github.com/v-fox/live_opensuse_hsf/blob/master/source/images.sh) to forbid kernel/initrd stripping. And there were no fail check for mounting /cow, so it were creating cow-file in initrd's tmpfs, hence its disappearance.

Why would it do that and how the hell am I to add third-party kernel modules to initrd now (config.xml 'drivers' directive takes only paths under /kernel directory but they are in /updates & /extras) ?

**Comment by schaefi** [comment]
commit 3b5a64d2dd5603e53c4d39f73aa5d38c8d3f3823 addressing the issues discussed here

**Comment by ulkuderner** [comment]
Is it possible to apply this on OEM image as well? Or hook it before arranging MBR and partitioning?
