### ISSUE TITLE
kiwi breaks JeOS build

### ISSUE THREAD

**Issue by andreas-schwab** [openSUSE/kiwi#478]
[  506s] Aug-08 09:13:49 <1> : Calling pre bootloader install script:
[  506s] Aug-08 09:13:49 <1> : --> uboot-image-efi-setup
[  506s] bash: uboot-image-efi-setup: No such file or directory
[  506s] Aug-08 09:13:49 <3> : Call failed, see console log

**Comment by schaefi** [comment]
Should have been fixed with this commit #3e694cc66

**Comment by schaefi** [comment]
actually Dirk Müller reported this was working again.
