### ISSUE TITLE
kiwi_LVM_LVboot_grub2_i386-pc=freespace:20: command not found

### ISSUE THREAD

**Issue by lnussel** [openSUSE/kiwi#503]
In some build logs I see the following message:

[  133s] Oct-09 06:51:06 <1> : images.sh: /.profile: line 1: kiwi_LVM_LVboot_grub2_i386-pc=freespace:20: command not found

Looks like kiwi doesn't transform some volume names properly to shell variables.

The kiwi file has an entry &amp;volume name="boot/grub2/i386-pc"/&amp; so I guess that's where it's coming from.

**Comment by schaefi** [comment]
Moved to v8 code stream

https://github.com/SUSE/kiwi/issues/39
