### ISSUE TITLE
kiwi initrd bloating: binutils

### ISSUE THREAD

**Issue by matwey** [openSUSE/kiwi#507]
initrd generated by armv7l/oemboot/suse-tumbleweed boot config contains binutils package (which includes linker scripts (about 6MB) for a number of architectures) whereas only /usr/bin/strip (500KB) is required for dracut. Is it possible to do something with it to reduce initrd size?

**Comment by schaefi** [comment]
https://doc.opensuse.org/projects/kiwi/doc/#sec.bootcustomization
