### ISSUE TITLE
kiwi is lacking compression options & seems to be ignoring --gzip-cmd directive

### ISSUE THREAD

**Issue by v-fox** [openSUSE/kiwi#512]
It seems that kiwi is hardcoded to use gzip with maximum compression so much so it still does it if you set '--gzip-cmd=lzop' option:
"`cpio --create --format=newc --quiet | gzip -9 -f`" is in the log despite
"`Setting gzip command to: lzop`" being there.

gzip compression is not as good as xz and as not as fast as lzo. So it would be nice to have options for that. For my personal purpose speed is more important than space saving, so I would rather go with lzo with minimal compression ratio.

**Comment by schaefi** [comment]
yes for the purpose of building the initrd the custom compression option does not apply. This is an inconsistency I'm going to fix in the new version of kiwi (see horizon branch). For now I'm not touching this part but you can go with a $HOME/.kiwirc files as follows

```perl
our $Gzip = 'lzop'
```

That changes it for the entire application
