### ISSUE TITLE
rpmbuild fails on SLES12

### ISSUE THREAD

**Issue by rpasche** [openSUSE/kiwi#526]
Hi,

I'm trying to build kiwi from the current master branch on a SLES12 server. rpmbuild fails within "test" with

```
ok PASS Test::kiwiXMLValidator::test_volumeNameAttrNoWhiteSpace
ok

Test Summary Report
-------------------
./KTImageCreator.t              (Wstat: 0 Tests: 7 Failed: 3)
  Failed tests:  5-7
./KTXMLInfo.t                   (Wstat: 0 Tests: 15 Failed: 9)
  Failed tests:  7-15
Files=47, Tests=1542, 23 wallclock secs ( 0.32 usr  0.02 sys + 14.12 cusr  2.56 csys = 17.02 CPU)
Result: FAIL
Makefile:232: recipe for target 'test' failed
make: *** [test] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.VqoaeT (%check)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.VqoaeT (%check)
```

At least 2 errors within KTImageCreator seem to be caused by missing README.txt file. I'm currently not able to further debug the "tests" :-(

Do you have any hints to fix this?

Regards,
Robert

**Comment by schaefi** [comment]
builds fine here:

https://build.opensuse.org/package/binaries/Virtualization:Appliances/kiwi?repository=SLE_12

no idea why the tests fails on your side. I guess the build environment is missing some core stuff ?

you can run

```
osc checkout Virtualization:Appliances kiwi
cd Virtualization:Appliances/kiwi

osc build SLE_12 x86_64
```

that will setup a chroot and builds the package, I have tested that and thus I think your system you run rpmbuild on is missing something

**Comment by rpasche** [comment]
well....that worked pretty well. Now I can try new kiwi.

Thanks a lot.
