### ISSUE TITLE
kiwi removes all 3rd-party modules from initrd

### ISSUE THREAD

**Issue by v-fox** [openSUSE/kiwi#529]
I finally fixed pretty much everything in hybrid persistency feature and was ready to make a live image release then on latest builds [kiwi decided for now reason to start removing "updates" and "extra" folders from under /lib/modules/\<kernel\>](https://github.com/openSUSE/kiwi/issues/475#issuecomment-164003377), despite [those packages having `bootinclude="true"` parameter](http://pastebin.ca/3284858) and being tested working for more than half a year.

And I have suspicion that directives `suseStripKernel` and `suseStripInitrd` images.sh don't strip initrd but instead remove **all** kernel modules from actual image and do nothing with actual initrd, respectively.
And even if you do something as insane as removing modules from image and not initrd for some reason, you should somehow make those in initrd available to the running system.

**Comment by v-fox** [comment]
It seems that [this](https://github.com/openSUSE/kiwi/commit/ea315c4a2e00aec10ad1644885ad1e2197794325) was the offending commit and [this one](https://github.com/openSUSE/kiwi/commit/09c410bccb567a06fa975844124e61b011086173) reverts its breakage. BUT it still doesn't answer my questions "why the hell it strips anything while I explicitly forbid it ?" and "why all of my modules are gone from system image and initrd not any less smaller then suseStripKernel and suseStripInitrd are uncommented in images.sh ?".

Also, the explanation for latter commit lies about how "suseStripKernel took the update and weak-update modules only into account if they are mentioned in the drivers list". It didn't took nothing, I've put
```
    <drivers>
        <file name="*"/>
    </drivers>
```
into config.xml and it still nuked everything the same exact way.

Aaaand 'extra' directory is still ignored despite there being a module with `bootinclude="true"`.

**Comment by schaefi** [comment]
I think the problem is that suseStripKernel and suseStripInitrd should be only used for the boot (initrd) descriptions kiwi provides but not for the user system image descriptions. If you add a custom <drivers> section it will be used for the implicit boot image (initrd) creation but not for the system image. Thus using the strip methods in config.sh/images.sh of a system image will break the image. That's correct. I passed on this information to the documentation team

Thanks
