### ISSUE TITLE
[RFE] Support building rpm-ostree repository and images

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/kiwi#530]
Please add support for [rpm-ostree](https://github.com/projectatomic/rpm-ostree/) repositories and images. With rpm-ostree, you can create versioned filesystem trees to provide atomic, reliable upgrades. "git-like" management of appliances would be pretty sweet.

**Comment by schaefi** [comment]
Adding it to the features list

**Comment by schaefi** [comment]
Issue has been moved to the v8 kiwi code base

https://github.com/SUSE/kiwi/issues/38
