### ISSUE TITLE
No support for DNF

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/kiwi#538]
In Fedora, Yum has been replaced with DNF. Please add support for DNF so that KIWI can be used for building Fedora based images.

**Comment by schaefi** [comment]
Thanks, I'm going to address this in the next generation code of kiwi here: https://github.com/SUSE/kiwi

At the moment we have only very limited resources to add more. I apologize if this will sit for a while

**Comment by Conan-Kudo** [comment]
@schaefi why is the new kiwi in the SUSE org rather than the openSUSE org?

**Comment by schaefi** [comment]
I think I put it there because the openSUSE-xyz name for the distribution is gone. That's now called 'Leap' or 'Tumbleweed' and just SUSE as organization name matches both SUSE and openSUSE

There was no real technical reason. If you see a problem don't hesitate to let us know

Thanks

**Comment by schaefi** [comment]
Feature has been moved to the v8 code base

https://github.com/SUSE/kiwi/issues/36
