### ISSUE TITLE
grub2 oem with overlayfs - empty grub.cfg

### ISSUE THREAD

**Issue by magist3r** [openSUSE/kiwi#540]
Hi!
I create oem image with overlayfs filesystem. In this case grub2 cannot create config on installed system:
grub2-probe: failed to get canonical path of 'overlayfs'
This is from boot.kiwi logfile.
I think this is a grub2 bug and I don't know can it be fixed in kiwi at all. grub works fine with same config.

Offtopic:
Can I somehow update my image in the future without data loss? For now I have 3 partitions:
boot
read-only
read-write
So I need to somehow set size for read-only (if my image will be bigger than now) and rewrite only boot and read-only partitions on update without touching read-write. This approach is very useful for embedded systems. Is it possible with kiwi?

**Comment by schaefi** [comment]
Hi,

>    I create oem image with overlayfs filesystem In this case grub2 cannot
>    create config on installed system:
>    grub2-probe: failed to get canonical path of 'overlayfs'
>    This is from bootkiwi logfile
>    I think this is a grub2 bug and I don't know can it be fixed in kiwi at
>    all grub works fine with same config

yes this is a well known grub2 bug. I'm afraid I can't workaround this
from the kiwi side.

>    Offtopic:
>    Can I somehow update my image in the future without data loss? For now
>    I have 3 partitions:
>    boot
>    read-only
>    read-write
>    So I need to somehow set size for read-only (if my image will be bigger
>    than now) and rewrite only boot and read-only partitions on update
>    without touching read-write This approach is very useful for embedded
>    systems Is it possible with kiwi?

kiwi supports a partition based install method "oem-partition-install"
However the use case is more to protect other OS'es on the disk. I never
have tested what happens if you use an older write space when the origin
partition is updated. My feeling says it could cause quite some trouble

**Comment by schaefi** [comment]
closing, should be fixed in grub2
