### ISSUE TITLE
Image creation with installstick and installiso enable is not consistent

### ISSUE THREAD

**Issue by M0ses** [openSUSE/kiwi#542]
If I set installstick=true, I get as result two working files:

* raw.install.raw.xz
* raw.xz

If I set " installstick=true  installiso=true" I get as result:

* .iso (working)
* .raw.install.raw.xz (working)
* .raw.xz ( only a string inside "xz  ... install.raw ... No such file or directory")

seen in OBS:Server:Unstable
please note that we already switched to "installiso=true hybrid=true" for other reasons, so the failure will not be visible there any longer.

**Comment by schaefi** [comment]
I found the bug and fixed it. Thanks for reporting this
