### ISSUE TITLE
Errors when converting raw images with LVM with "kiwi --convert"

### ISSUE THREAD

**Issue by ipeoshir** [openSUSE/kiwi#554]
Logs from below shows that kiwi is not processing raw images with LVM as it should and then it cannot convert raw images to different formats (vhd, qcow2, etc.).

linux:~ # kiwi --version
Feb-29 12:16:26 <1> : Version:
Feb-29 12:16:26 <1> : --> vnr: 7.03.58
Feb-29 12:16:26 <1> : --> git: 0a18e00e380b8c8090bf8eb0e2ae8e1f3331e18e
linux:~ # kiwi --logfile terminal --convert SLES12.x86_64-12.0.0.0.100.raw --format qcow2
Feb-29 12:16:36 <1> : Setting log file to: terminal
Feb-29 12:16:36 <1> : kiwi --logfile terminal --convert SLES12.x86_64-12.0.0.0.100.raw --format qcow2
Feb-29 12:16:36 <1> : kiwi revision: 0a18e00e380b8c8090bf8eb0e2ae8e1f3331e18e
Feb-29 12:16:36 <1> : Setting log file to: terminal
Feb-29 12:16:36 <1> : EXEC [/usr/bin/uname -m]
Feb-29 12:16:36 <1> : --> Starting image format conversion...
Feb-29 12:16:36 <1> : EXEC [mktemp -qdt kiwiread.XXXXXX]
Feb-29 12:16:36 <1> : EXEC [blkid SLES12.x86_64-12.0.0.0.100.raw -s TYPE -o value 2>/dev/null]
Feb-29 12:16:36 <1> : EXEC [blkid -o value -s TYPE SLES12.x86_64-12.0.0.0.100.raw]
Feb-29 12:16:36 <1> : EXEC [dd if=SLES12.x86_64-12.0.0.0.100.raw bs=128k count=1 2>/dev/null | grep -qi CLIC]
Feb-29 12:16:36 <1> : EXEC [blkid SLES12.x86_64-12.0.0.0.100.raw -s PTTYPE -o value 2>/dev/null]
Feb-29 12:16:36 <1> : EXEC [/sbin/losetup  -f --show SLES12.x86_64-12.0.0.0.100.raw 2>&1]
Feb-29 12:16:36 <1> : EXEC [kpartx -sa /dev/loop2 2>&1]
Feb-29 12:16:36 <1> : EXEC [udevadm settle --timeout=30 2>&1]
Feb-29 12:16:36 <1> : EXEC [pvs --noheadings -o vg_name /dev/mapper/loop2p3 2>/dev/null]
Feb-29 12:16:36 <1> : EXEC [mount -n /dev/mapper/loop2p3 /tmp/kiwiread.TSEe2N 2>&1]
Feb-29 12:16:36 <1> : EXEC [blkid -o value -s TYPE /dev/mapper/loop2p3]
Feb-29 12:16:36 <3> : Expected a directory at /tmp/kiwiread.TSEe2N/image.
Specify a directory as the configuration base.
Feb-29 12:16:36 <3> : Could not find specified configuration: undefined
Feb-29 12:16:36 <1> : EXEC [sync]
Feb-29 12:16:37 <1> : EXEC [umount /tmp/kiwiread.TSEe2N 2>&1]
Feb-29 12:16:37 <1> : EXEC [kpartx -sd /dev/loop2 2>&1]
Feb-29 12:16:37 <1> : EXEC [losetup -d /dev/loop2 2>&1]
Feb-29 12:16:37 <1> : Closing session with ecode: 1
Feb-29 12:16:37 <3> : KIWI exited with error(s)

**Comment by schaefi** [comment]
Hmm, just tested this today and it worked for me. I got

```
Mar-01 15:38:42 <1> : EXEC [pvs --noheadings -o vg_name /dev/mapper/loop1p3 2>/dev/null]
Mar-01 15:38:42 <1> : EXEC [vgchange -a y systemVG 2>&1]
```

Can you tell me the pvs output:

```
$ losetup -f --show SLES12.x86_64-12.0.0.0.100.raw
$ kpartx -sa /dev/loopX
$ pvs --noheadings -o vg_name /dev/mapper/loopXp3
```

Thanks

**Comment by ipeoshir** [comment]
linux:~ # ls -l
total 2942000
-rw-r--r-- 1 root root 53687091200 Feb 29 12:16 SLES12.x86_64-12.0.0.0.100.raw

linux:~ # losetup -f --show SLES12.x86_64-12.0.0.0.100.raw
/dev/loop2

linux:~ # kpartx -sa /dev/lo
log           loop-control  loop0         loop1         loop2         loop3         loop4         loop5         loop6         loop7

linux:~ # kpartx -sa /dev/loop2
linux:~ # pvs --noheadings -o vg_name /dev/mapper/loop2p
loop2p1  loop2p2  loop2p3  loop2p4

linux:~ # pvs --noheadings -o vg_name /dev/mapper/loop2p3
  No physical volume label read from /dev/mapper/loop2p3
  Failed to read physical volume "/dev/mapper/loop2p3"
linux:~ # pvs --noheadings -o vg_name /dev/mapper/loop2p
loop2p1  loop2p2  loop2p3  loop2p4
linux:~ # pvs --noheadings -o vg_name /dev/mapper/loop2p4
  systemVG

**Comment by ipeoshir** [comment]
We also use a swap in our config.xml:

      <systemdisk name="systemVG">
        <volume name="swap" size="6144"/>
      </systemdisk>

**Comment by schaefi** [comment]
Hmm, I see the lvm sits on p4  but kiwi looks at p3. Could you send the <type> section so that I can build the same layout you are using. Sorry for asking so many questions

**Comment by ipeoshir** [comment]
Oh, let me know if there is anything else I could help you with...

This is a simplified version of the config.xml:
<?xml version="1.0" encoding="utf-8"?>
<image schemaversion="5.8" name="__NAME__">
  <profiles>
    <profile name="appliance" description="SLES12"/>
  </profiles>
  <preferences>
    <version>__VERSION__</version>
    <packagemanager>zypper</packagemanager>
    <bootsplash-theme>SLES</bootsplash-theme>
    <bootloader-theme>SLES</bootloader-theme>
    <rpm-excludedocs>false</rpm-excludedocs>
    <locale>en_US</locale>
    <keytable>us.map.gz</keytable>
    <timezone>US + Canada/Eastern Time</timezone>
    <hwclock>utc</hwclock>
  </preferences>
  <preferences profiles="appliance">
    <type image="vmx" filesystem="ext3" boot="vmxboot/suse-SLES12" primary="true" format="vmdk" bootloader="grub2" firmware="efi" kernelcmdline="splash">
      <systemdisk name="systemVG">
        <volume name="swap" size="6144"/>
      </systemdisk>
      <machine memory="4096" guestOS="sles12-64" HWversion="7" arch="x86_64">
        <vmdisk controller="lsilogic" id="0"/>
        <vmdvd  controller="ide" id="0"/>
        <vmnic driver="vmxnet3" interface="0" mode="bridged"/>
      </machine>
      <size unit="G">50</size>
    </type>
  </preferences>
  <users group="root">
    <user password="" home="/root" name="root"/>
  </users>
  <repository type="yast2" priority="3">
    <source path="/slesmedia/12-SLES-DVD1"/>
  </repository>
  <packages type="image" profiles="appliance">
    <package name="zypper"/>
  </packages>
  <packages type="bootstrap">
    <package name="ca-certificates"/>
    <package name="cracklib-dict-full"/>
    <package name="filesystem"/>
    <package name="udev"/>
  </packages>
</image>

**Comment by schaefi** [comment]
Thanks, I think I found the bug, testing my fix

**Comment by schaefi** [comment]
yep found and fixed, will submit new packages in a minute
