### ISSUE TITLE
KIWICollect

### ISSUE THREAD

**Issue by k0da** [openSUSE/kiwi#564]
There are cases where noarch is combined across target architectures, and it could be noarch build by architecture1 have different version than noarch built by architecture2.

In that case first seen package is picked. IMO kiwi should pick the one with higher version.

Example grub2 package have grub2-snapper-plugin noarch package.
it was built for ppc ppc64 and ppc64le architectures, but later ppc was build disabled so version update didn't happen for ppc. As the result ftp repo have grub2-snapper-plugin package from ppc repo. Which got unresolved as it requires older grub2 binary

**Comment by k0da** [comment]
I think we'd need @adrianschroeter and @mlschroe help here

**Comment by adrianschroeter** [comment]
the version should be identical in first place. If it isn't something else seems to be broken.

if you disable a package build and want it not to be used anymore you need also to wipe it.

Nothing which should be solved in kiwi IMHO.

**Comment by k0da** [comment]
I don't want to wipe binaries, somebody else still could install them. The point is I build ftp only for ppc64 and ppc64le but I got ppc's noarch there accidentally

**Comment by k0da** [comment]
Oh, it is not only about grub.. but yast!
