### ISSUE TITLE
question doesn't appear in kiwi.pdf

### ISSUE THREAD

**Issue by rdesfo** [openSUSE/kiwi#568]
The question "My customized boot image refuses to boot. How to debug?" doesn't appear in the kiwi.pdf.

https://github.com/openSUSE/kiwi/blob/589e9359a28d2d9105f0321974b83a9929fb23b1/doc/docbook/xml/kiwi-doc-workflow.xml#L995

**Comment by schaefi** [comment]
@tomschr do you have an idea why this is missing in the compiled result ?

Thanks

**Comment by tomschr** [comment]
@schaefi @rdesfo  It seems the stylesheets have some deficiancies. You have to move the `indexterm`s into the `para` element to avoid it.

I could successfully build it with these modifications. Your question will appear:

```xml
<qandaentry>
    <question>
     <para><indexterm>
      <primary>KIWI</primary>
      <secondary>boot parameters</secondary>
     </indexterm>
      <indexterm>
       <primary>boot parameters</primary>
      </indexterm>
      My customized boot image refuses to boot. How to debug?
     </para>
    </question>
    <answer>
      ...
    </answer>
   </qandaentry>
```
