### ISSUE TITLE
Enable SELinux during the initrd phase in CentOS 6.7 / kernel 2.6.32.x

### ISSUE THREAD

**Issue by andrey01** [openSUSE/kiwi#569]
Dear Devs/Hackers,

I am wondering whether there is a way to keep SELinux enabled whilst being loaded into Kiwi's `/boot/initrd.vmx` ?

I did a simple `config.xml` for the CentOS 6.7 x86_64, the deployment works fine, unless the SELinux is working only on the 3rd boot.

- The 1st boot the `initrd.vmx` is loaded with the SELinux disabled (completely disabled); it the starts `dracut` that generates the right initrd file which enables the SELinux then;
- During the 2nd boot the SELinux sees that it needs to relabel the FS (creates `/.autorelabel` file) => OK
- With the 3rd boot SELinux is fully working => OK

So my question is, would it be possible to do some modifications either to the Kiwi build system, or leverage the `kiwi-boot` hooks, or "hack" the Kiwi's `initrd.vmx` file in order to make the SELinux initialize at the 1st boot?

Thanks a million for helping with this! :)

P.S.
Currently I have been checking CentOS 6.7 vs CentOS 7.2 and noticed that CentOS 7.2 has SELinux enabled with the first boot.

I've also placed `exec sh` after `selectLanguage` in the `initrd.vmx:/init` so that I can check the differences and found that in CentOS 6.7 there is no `/sys/fs/selinux` directory, and in CentOS 7.2 there is `/sys/fs/selinux` and as well as `/sys/kernel/slab/selinux_inode_security`

CentOS 6.7 has the `2.6.32-573.22.1.el6.x86_64` kernel
CentOS 7.2 has the `3.10.0-327.13.1.el7.x86_64` kernel

**Comment by andrey01** [comment]
dmesg for CentOS 6.7:

```
SELinux: Initializing.
SELinux: Starting in permissive mode
SELinux: Registering netfilter hooks
```

dmesg for CentOS 7.2:

```
SELinux: Initializing.
SELinux: Starting in permissive mode
SELinux: EVM: security.selinux
SELinux: Registering netfilter hooks

.. and then there are more SELinux-related messages since the rules being applied => normal ..
```

**Comment by schaefi** [comment]
I'm addressing all of this in the new kiwi version:

* the setup of the SELinux security policy (labeling) has been done in
  https://github.com/SUSE/kiwi/issues/52

* for the initrd you have the choice to use the dracut initrd instead of the kiwi initrd with

```xml
  <type ... initrd_system="dracut"/>
```

If we are missing more e.g apply selinux policy for kiwi initrd too, please open an issue on the SUSE/kiwi project issue page

Thanks

**Comment by schaefi** [comment]
Closing the issue for the legacy kiwi

**Comment by andrey01** [comment]
Thank you very much @schaefi !


Also, just for my record (and for someone else who will encounter this):

```
-bash-4.1# mount -t selinuxfs selinuxfs /selinux
-bash-4.1# sestatus 
SELinux status:                 enabled
SELinuxfs mount:                /selinux
Current mode:                   enforcing
Mode from config file:          permissive
Policy version:                 24
Policy from config file:        targeted
```

**Comment by arno01** [comment]
@schaefi The kiwi-ng does not seem support RHEL6 (CentOS6) :-/
The legacy kiwi does not have the `initrd_system` type.

What would be a solution to CentOS6 ? I understand that it would be good to upgrade it, however we are still using it to some extent.

P.S. with the above manual selinuxfs mount, the system is still not in a good state since `id -Z` does not output "unconfined". Maybe some SELinux folks might know whether this could be workarounded without a reboot?

**Comment by andrey01** [comment]
Seems I have been able to work this around :-) 

```
bash-4.1# diff -u init.bkp init
--- init.bkp	2016-04-21 10:53:07.000000000 -0400
+++ init	2016-04-26 03:29:16.935104761 -0400
@@ -678,6 +678,14 @@
 cp /preinit /mnt
 cp /include /mnt
 
+
+# 23-24) enable SELinux
+LANG=C chroot /mnt /sbin/load_policy -i
+echo 0 > /mnt/selinux/enforce
+mount --bind /dev "/mnt/dev"
+LANG=C chroot "/mnt" /sbin/restorecon -F -R /dev
+
+
 #======================================
 # 24) kill boot shell
 #--------------------------------------
bash-4.1# 
```

Gives me `unconfined` and proper `ps auxZ` output... things are just working great :) `load_policy` itself takes care of mounting the selinuxfs :]

**Comment by schaefi** [comment]
>    Seems I have been able to work this around :-)

Thanks, I have put this into its own method loadSELinuxPolicy()
and call it from the rhel-preinit phase of the kiwi initrd

See commit 8d507e049d94 for details
