### ISSUE TITLE
Suggestion/Idea: wait for the loopback device to be free / modular approach when writing the bootloader

### ISSUE THREAD

**Issue by andrey01** [openSUSE/kiwi#574]
@schaefi Hello Marcus,

Just came to my mind, how about to make kiwi (v7 if possible & v8) to wait for the loopback (/dev/loopX) device before attempting to write the bootloader section in it?
This way the person who builds the image does not need to restart the whole build process again, but instead, he could clearly see the evidence and intervene (e.g. to clean-up loopback devices).

And in automation (e.g. Docker / Jenkins jobs, ...), it would be really nice if the jobs could actually wait (with the timeout ofc) for the loopback device to be free. That way we would not be afraid to run Kiwi in parallel without being afraid of the loopback device exhaustion.

Regarding the modular approach, it would be really nice in such scenario, when one builds the image, but Kiwi fails to write the bootloader (due to grub vs. FS-type/feature problem, free loopback device timeouts, etc..), and then one could simply do something like `kiwi --root path/to/image/root-tree --write-grub path/to/image.raw` instead of waiting the relatively long process until he gets the `image.raw` file.

Let me know what do you think?

Thanks

**Comment by schaefi** [comment]
Hmm, just thinking about this. So in normal mode kiwi requests the next free loopback device by calling losetup with the --show option. In case you have 7 loop device nodes you will run into an exception if all seven are in use. This could happen if you e.g run 7 parallel docker builds which
then consumes all loop devices of the host kernel

In such a case you suggest to wait until one gets free again, is that correct ?

If so this sounds like a nice idea, however I don't see how we can wait "intelligently",
I think we can only wait until a timeout is reached.

I'm not going to add more features to the v7 code base, thus it would be great if you can move this issue to https://github.com/SUSE/kiwi/issues

Thanks

**Comment by andrey01** [comment]
I understand. Yes, the timeout would be a must, since we would not want to have "zombie"-kiwi instances forever waiting for the /dev/loopX to be available .. :-)

The only sad thing for us is that kiwi-ng (v8) does not support RHEL6 based images and the legacy grub.

Thanks

**Comment by schaefi** [comment]
> The only sad thing for us is that kiwi-ng (v8) does not support RHEL6 based images and the legacy grub

that's true. On a short look in v7 I would say if the patch is only adding a losetup retry in KIWIGlobals::loop_setup() method, activated by an explicit command line option and thus not changing the default behaviour, I'm sure a patch will be merged and submitted to the maintained code base

It's a matter of time and resources. Currently my plate is full with public cloud work and getting kiwi v8 into SLE12, Leap

I'm happy for any code contributions :smile:

**Comment by andrey01** [comment]
@schaefi I would be delighted to send some meaningful PR in this matter, but of course, we are also constrained by the time since we are doing the "agile" thing... :P   In case if I will do such work, you will be nearly the 1st to know about it (via PR) ;-)

**Comment by schaefi** [comment]
I'm used to the "agile" thing... aka scrum :) Maybe your planning allows this one to be part of the sprint at some time. Thanks

**Comment by andrey01** [comment]
@schaefi so we can talk the same language ;-) I am afraid our PO won't see a great business value behind this, since he has a lot of more high-priority things :-)  And this was just my personal idea.. this does not hurt us (yet) since we do not generate lots of images, but just seldom :)

So this issue might be a good for some "FUTURE/TODO" list or => WANTED.md for the kiwi-ng :-)  so the future contributors would know how and where they can contribute ;)

**Comment by schaefi** [comment]
yep, makes all sense to me

**Comment by schaefi** [comment]
Closing on behalf of https://github.com/SUSE/kiwi/issues/82
