### ISSUE TITLE
kiwi fails to build sles image when type is vmx and vmdisk controller="scsi" it works when controller="ide" is mentioned 

### ISSUE THREAD

**Issue by arjunm183** [openSUSE/kiwi#580]
kiwi fails to build sles image when type is vmx and vmdisk controller="scsi". Tt works when controller="ide" is mentioned 

Operating System : SLES 12 SP1
Version of Kiwi : 
kiwi-tools-7.02.77-1.1.x86_64
kiwi-desc-vmxboot-7.02.77-1.1.x86_64
kiwi-doc-7.02.77-1.1.noarch
kiwi-desc-isoboot-7.02.77-1.1.x86_64
kiwi-templates-7.02.77-1.1.x86_64
kiwi-7.02.77-1.1.x86_64

This is the config file which i use .  

preferences profiles="vmxFlavour"
vmdisk controller="scsi" id="0"

When i build the image it gives the error Schema validation failed . Looks like a bug.Kindly help .

**Comment by schaefi** [comment]
scsi is an invalid controller name as the schema validation told you, allowed are

```
attribute controller {
            "ide"        |
            "buslogic"   |
            "lsilogic"   |
            "lsisas1068" |
            "legacyESX"  |
            "pvscsi"
        }
```

I normally use lsilogic for scsi controller emulation in vmware

If this has changed in VMware and there are other controller types available please let me know
