### ISSUE TITLE
[kiwi] building initrd in the background for vmx causes system not to boot after

### ISSUE THREAD

**Issue by mmohring** [openSUSE/kiwi#582]
I can confirm that with KIWI v7.03.70 the race condition of calling dracut in the background can generate for a virtual machine a unbootable system. I will check if this is fixed with the new version v7.03.71 you had just been creating. I have tested this bug for openSUSE Leap 42.1 and 42.2 just now. Will test now for v7.03.71 and report.

**Comment by mmohring** [comment]
I had to call `> mkinitrd` by hand, this fixed the problem. One more indication. I will check v7.03.71 next.

**Comment by schaefi** [comment]
yes, a bad one :( fixed now, new packages available v7.03.71 (v8 does not have this problem)

**Comment by mmohring** [comment]
I have tested the fix and problem is gone.

**Comment by mmohring** [comment]
I have tested with git commit 0f34258da5dc0edcd3f28b730b47484c8b51086b that it works. That is the v7.03.71 git commit.

**Comment by schaefi** [comment]
Thanks much :+1:
