### ISSUE TITLE
shim setup is failing on RH7 based system

### ISSUE THREAD

**Issue by k0da** [openSUSE/kiwi#594]
There are couple issues with building uefi oem image for CentOS7
1) shim-install seems to be SUSE specific tool and not available for other distros
2) shim location is not /usr/lib64 but /boot/efi/EFI/centos/shim.efi

**Comment by schaefi** [comment]
Hi sorry for the late reply

Hmm, I haven't thought about shim-install to be suse specific. It does a lot of stuff, more than just copying the shim.efi binary to the right place.

Does RH have their own shim setup tool ?

**Comment by schaefi** [comment]
I agree it would be good to find a solution which works for all distros

**Comment by schaefi** [comment]
This issue is addressed in the next generation kiwi here:
https://github.com/SUSE/kiwi/pull/348
