### ISSUE TITLE
NeedInfo: Where do you keep your previous kiwi8 RPM builds?

### ISSUE THREAD

**Issue by lawre** [openSUSE/kiwi#603]
We have run into an issue after updating to the 8.21.x kiwi-tools-8 line and we need to downgrade to an earlier version (8.20.x) to isolate where the break occurred.  Where do you keep these archived?

**Comment by schaefi** [comment]
The plan for old releases is to host them here:

* https://pypi.python.org/pypi/kiwi

Unfortunately I made a mistake with the already released sources which causes _pip_ to fail the installation. It might work if you install via:

```
pip install --egg kiwi==<version>
```

For newer releases I have fixed the python setup code to work with pip. Thus if you have trouble installing old releases there is only the way through git which works as follows:

```
git clone https://github.com/SUSE/kiwi.git
git tag --list

==> see all the tags

git checkout <tag-name>

pip install -r .virtualenv.dev-requirements.txt

tox -e doc

python setup.py build
python setup.py install
```

I'm sorry for any inconvenience with regards to old releases

Hope that helps

**Comment by schaefi** [comment]
pip install has been fixed to work for the current versions also without --egg
