### ISSUE TITLE
Support for openSUSE 42.2

### ISSUE THREAD

**Issue by cboltz** [openSUSE/kiwi#611]
Theo tried to build a 42.2 JeOS image which failed with

> [  136s] Oct-10 10:35:49 <3> : Could not find valid boot image description for'oemboot/suse-leap42.2'.
> [  136s] Oct-10 10:35:49 <3> : The required boot image description: 'oemboot/suse-leap42.2' for the selected build type: 'oem' does not exist.

(see https://build.opensuse.org/package/live_build_log/openSUSE:infrastructure:Images:openSUSE_Leap_42.2/jeos/images/x86_64 for the full log)

This is not too surprising because https://github.com/openSUSE/kiwi/tree/master/template/ix86 doesn't have a template for 42.2 yet.

Can you please create the 42.2 template and submit it to 42.2 and whereever else it is needed to build a 42.2 image?

(cc @ccboltz)

**Comment by schaefi** [comment]
Support for Leap >= 42.2 is implemented in the next generation kiwi which you can find here:

http://suse.github.io/kiwi

the v7 version of kiwi can be used up to SLE12 and/or Leap 42.1. Beyond there is the switch to v8.
You don't have to change your image description, also see:

http://suse.github.io/kiwi/legacy_kiwi.html

For dropped features and the reason behind all this. If you have problems building with v8 do not hesitate to contact us via the mailing list or on the kiwi-ng github:

https://github.com/SUSE/kiwi

Thanks

**Comment by cboltz** [comment]
Thanks for the information. I'm happy to hear that v8 supports 42.2.

Unfortunately 42.2 (and also Factory) still contain v7 (last updated some days ago to 7.04.8), so - how should we build 42.2 images? It looks like this needs v8, but this version is not in 42.2...

I also found https://build.opensuse.org/package/show/home:mkravec:JeOS:Leap:42.2/kiwi-templates-Leap42-JeOS which looks like a possible workaround. However I don't like the idea of having a package from a home repo as BuildRequires when building an image.

BTW: If you think this is the wrong place to discuss this, please point me to a better location.

**Comment by schaefi** [comment]
The v8 version is not a replacement for v7, v7 and v8 can and will co-exist for a while. Think about people who want to build e.g SLE11 images on a Leap 42.2 build host

Regarding v8 not available on Leap 42.2. This is correct the Leap team is currently discussing if they will accept my submission of python3-kiwi (v8 kiwi package). Thus this is work in progress but outside of my control

Until the package has been accepted you can build in the buildservice as documented here:

http://suse.github.io/kiwi/quickstart.html#using-kiwi-ng-from-build-service

There is no need to have an unofficial home repo added to build with v8

Hope that helps
