### ISSUE TITLE
Wrong mount order when specifing nested mount points in LVM groups

### ISSUE THREAD

**Issue by davidcassany** [openSUSE/kiwi#621]
If several partitions are defined for a _vmx_ image and they contain nested mount points, as in the `systemdisk` configuration shown below, `/var/log` get mounted before `/var`. Apparently this is due to the names, as the volume attributes are stored in a HASH where the key for each volume is the volume name. Then looping over that HASH results in an alphabetical order which ends up also setting the mount order.

```xml
<systemdisk name="vg0">
  <volume name="@root" size="4G"/>
  <volume name="LVhome" size="1G" mountpoint="home"/>
  <volume name="LVtmp" size="2G" mountpoint="tmp"/>
  <volume name="LVopt" size="1G" mountpoint="opt"/>
  <volume name="LVvar" size="2G" mountpoint="var"/>
  <volume name="LVlog" size="2G" mountpoint="var/log"/>
</systemdisk>
```

The user should not have to care about that, mount should happen in appropriate order.

**Comment by schaefi** [comment]
Hi,

>    If several partitions are defined for a vmx image and they contain
>    nested mount points, as in the systemdisk configuration shown below,
>    /var/log get mounted before /var. Apparently this is due to the names,
>    as the volume attributes are stored in a HASH where the key for each
>    volume is the volume name. Then looping over that HASH results in an
>    alphabetical order which ends up also setting the mount order.

This should not happen, there is code in kiwi to address this
see: KIWIBoot.pm::setupBootDisk() search for "Create path names in correct order"

So if this is broken there seems to be a bug. We also addressed this in
the v8 version of kiwi but there it's solved much nicer and a test
exists

**Comment by davidcassany** [comment]
Thanks I will have a look at that code. There might be a bug somewhere because, I certainly had to rename volumes to get the above configuration mounted properly.
