### ISSUE TITLE
Interactive systemd-firstboot

### ISSUE THREAD

**Issue by davidcassany** [openSUSE/kiwi#628]
## Problem description

Deleting `/etc/machine-id` and dbus id files triggers _systemd-firstboot_ service. Which is a one shot service that runs when `/etc/machine-id` is missing.

## Actual behaviour

During first boot there are some interactive settings, actually _systemd-firstboot_ asks for locales, time zone and some other settings.

## Steps to reproduce the behaviour

Run a Leap 42.1 vmx that has been build with the KIWI v7.04.24. I should also effect SLE and openSUSE versions though.

Side effect of 0c9fa69901738b17dd2db378cf0f873831449ed7

**Comment by schaefi** [comment]
That sounds very bad. I thought systemd-firstboot is an optional service and needs a configuration like it was done for the JeOS images. It would be very bad if the change with the machine id would cause an interactive session on boot

**Comment by schaefi** [comment]
If that is all true we also have the problem in the v8 kiwi

**Comment by schaefi** [comment]
man you are right I knew we never should have touched it :(((((

**Comment by schaefi** [comment]
I'll fix this, thanks much for reporting

**Comment by davidcassany** [comment]
@schaefi I am testing a patch for that, from now it works in KIWI v7 for opensuse and testing right now with rhel.

I am using the systemd-firstboot command this way:

```bash
rm /etc/machine-id
if [ ! -L /var/lib/dbus/machine-id ];then
    rm -f /var/lib/dbus/machine-id
fi
systemd-firstboot --root=/ --setup-machine-id

```

**Comment by davidcassany** [comment]
@schaefi according to the docs the systemd-firsboot is supposed to used in preinit stages or on build image time ([systemd-firstboot](https://www.freedesktop.org/software/systemd/man/systemd-firstboot.html))

**Comment by schaefi** [comment]
no sorry I don't want to mess with that systemd stuff in the kiwi boot code. we are only opening a bunch of problems which are not our playground. If something can be controlled by systemd people can address this as part of their image configuration. This should not land in the kiwi boot code. See my open pull request
