### ISSUE TITLE
KIWIImageFormat.pm can´t remove a directory with a symlink in it, while creating ovf

### ISSUE THREAD

**Issue by floewe** [openSUSE/kiwi#633]
Hi,

kiwi failed to build an ovf
```
--
mv: '/opt/kiwi/GI1/image/oem/ISP2011GI.x86_64-57.1.4.ovf.tmp/ISP2011GI.x86_64-57.1.4.vmdk' and '/opt/kiwi/GI1/image/oem/ISP2011GI.x86_64-57.1.4.vmdk' are the same file

rmdir: failed to remove '/opt/kiwi/GI1/image/oem/ISP2011GI.x86_64-57.1.4.ovf.tmp': Directory not empty

Mar-03 01:34:30 <3> : Failed to move result image file(s) to destination: mv: cannot move '/opt/kiwi/GI1/image/oem/ISP2011GI.x86_64-57.1.4.ovf.tmp' to '/opt/kiwi/GI1/image/ISP2011GI.x86_64-57.1.4.ovf.tmp': Directory not empty
--
```

F20S-Test:/opt/kiwi/GI1/image/oem/ISP2011GI.x86_64-57.1.4.ovf.tmp # ll
total 0
lrwxrwxrwx 1 root root 31 Mar  3 02:12 ISP2011GI.x86_64-57.1.4.vmdk -> ../ISP2011GI.x86_64-57.1.4.vmdk

In line 340 there is a symlink created in $ovfdir
KIWIQX::qxx ("ln -s ../$img_base $ovfdir/$img_base");

In line 1303 $ovfdir moved to $ovfdir.tmp and in line 1305 everything within get moved to $destdir,
of course without the symlink from Line 340 -> same file

    KIWIQX::qxx ("mv $ovfdir $ovfdir.tmp");
    KIWIQX::qxx ("mkdir -p $destdir");
    KIWIQX::qxx ("mv -f $ovfdir.tmp/* $destdir")

In line 1306 $ovfdir.tmp should be removed. It fails cause it is not empty
    KIWIQX::qxx ("rmdir $ovfdir.tmp");

In my opinion the symlink must be removed before the rmdir 

Edit: Version 7.0.2 - SLES12-SP1

Edit 2: Can´t find The third error "Failed to move result image.." yet

**Comment by davidcassany** [comment]
@floewe thanks for such a detailed bug report it helps a lot, taking care of it will be my first task for next week.
