### ISSUE TITLE
kiwi setupNetwork should kill all interfaces and keep only prefered one on boot

### ISSUE THREAD

**Issue by k0da** [openSUSE/kiwi#638]
While booting kiwi image over the network, we run dhcpclien on all interfaces and check if we've got a lease from a server.

Then we proceed with the first one. But we could have situation when we started client on LACP configured port group and both interfaces got an address. In order to proceed we need to kill all other interfaces..

**Comment by schaefi** [comment]
Do you consider this to be a bug in the current handling or a special case ? if this is considered a bug please add the 'bug' label on it. If not please note that we are in maintenance mode with this version of kiwi and all enhancements will be handled in the new code base only on https://github.com/SUSE/kiwi

Thanks

**Comment by schaefi** [comment]
If still an issue please provide the information from the last comment. Thanks
