### ISSUE TITLE
Live ISO booting slower than with other live systems

### ISSUE THREAD

**Issue by probonopd** [openSUSE/kiwi#643]
Kiwi Live ISO booting is approximately 100% slower than with other live systems (e.g., Ubuntu casper or Fedora dracut). This is largely because the initrd is twice as large, and loading the initrd is a very slow copy operation. The reason for the large Kiwi initrd is that it contains many drivers and firmware files, which could also be loaded later in the boot process from the then-mounted squashfs.

So, is there a way to move all GPU and network driver loading to a later boot stage when the squashfs is available, and remove all GPU and network (if not interested in netbooting) related files from the Kiwi initrd?

**Comment by schaefi** [comment]
deleting data from the kiwi generated initrd can be done with a custom strip section in your XML description, like in the following example

```
<strip type="delete">
    <file name="/lib/firmware/..."/>
</strip>
```

Moving the loading of drivers to the systemd level would require additional work on the image

I agree the live iso setup kiwi provides is not focused on fast boot performance and I'm not sure if trying to address this in the kiwi initrd would be the right way.

You already mentioned that there are extensions to dracut available which supports live boot as well.
I was more thinking if it wouldn't be a good idea to make use of the dracut live iso support and modify kiwi's live iso image type in a way which makes the kiwi provided isoboot initrd obsolete.

We surely wouldn't do that in this version of kiwi which is in maintenance mode but in the next generation kiwi from here: https://github.com/SUSE/kiwi we already have support for dracut on the disk based images and I could imagine it would be better to support a broader used system instead of my kiwi specific isoboot system

Thoughts ?

**Comment by probonopd** [comment]
@schaefi my use case is building a live image for desktop usage that is optimized for boot time. I know I can use `<strip type="delete">`, but if I delete all of the firmware, will it then be loaded correctly in a later boot phase? That is what I'd need. I would be fine with either kiwi or dracut, as long as the ISO image can be produced on OBS. If this is possible only with https://github.com/SUSE/kiwi then let's continue discussion there.

**Comment by schaefi** [comment]
> but if I delete all of the firmware, will it then be loaded correctly in a later boot phase? 

The strip information applies only to the contents of the initrd. Thus if you keep the firmware which is
required to boot in your scenario you can delete all the rest. The same applies to e.g network drivers
or other parts of the kernel. If your live iso should only be able to boot from e.g the CD drive you could also consider to delete all of the usb stack and the disk drivers which would be needed when booting the image from a stick.

Please note kiwi checks for kernel module dependencies, thus even if you explicitly delete a module which is required by another one still included kiwi will pull it back in order to keep a consistent state

> as long as the ISO image can be produced on OBS. 

any version of kiwi no matter if it's the legacy or the next generation one is able to build the image in obs. It basically depends on the distribution of the image which kiwi version will be taken to build it in obs. Leap42.1 is the last version supported by kiwi v7, anything newer will use the next generation code base

Hope that helps

**Comment by probonopd** [comment]
Thanks @schaefi - could I remove all firmware from the squashfs with
```
<strip type="delete">
    <file name="/lib/firmware/"/>
</strip>
```
on Leap 42.2 and systemd would be smart enough to load all the firmware (e.g., for wireless) __after__ the squashfs has been mounted? Because I don't need the firmware for booting, but only once the system is up and running.

**Comment by schaefi** [comment]
yes that should work, the complete firmware has to still be present in the system after boot which allows for loading on demand

**Comment by probonopd** [comment]
On the initrd, there is 34 MB worth of `/usr/lib/grub2`. 
At the time when the initrd is loaded, the bootloader has already run, so why is this contained in the initrd? When I try to strip it, then kiwi is unable to produce the image, exiting with an error.
I compared with the Ubuntu initrd, it does not have this grub2 stuff in the initrd.

**Comment by probonopd** [comment]
Well, with

```
<strip type="delete">
    <file name="/lib/firmware/"/>
</strip>
```

I get on one of my machines

```
[    2.162048] [drm] radeon kernel modesetting enabled.
[    2.165306] radeon 0000:01:00.0: VRAM: 1024M 0x0000000000000000 - 0x000000003FFFFFFF (1024M used)
[    2.165308] radeon 0000:01:00.0: GTT: 1024M 0x0000000040000000 - 0x000000007FFFFFFF
[    2.165377] [drm] radeon: 1024M of VRAM memory ready
[    2.165377] [drm] radeon: 1024M of GTT memory ready.
[    2.165402] radeon 0000:01:00.0: Direct firmware load for radeon/CEDAR_pfp.bin failed with error -2
[    2.165403] r600_cp: Failed to load firmware "radeon/CEDAR_pfp.bin"
[    2.165447] [drm:evergreen_init [radeon]] *ERROR* Failed to load firmware!
[    2.165448] radeon 0000:01:00.0: Fatal error during GPU init
[    2.165449] [drm] radeon: finishing device.
[    2.172573] [drm] radeon: ttm finalized
[    2.172940] radeon: probe of 0000:01:00.0 failed with error -2
```

Graphics resolution and acceleration are not working. 

So apparently not all firmware is re-loaded at a later, post-initrd, stage.

**Comment by schaefi** [comment]
Concerning the grub2 packages as part of the initrd, I have created a pull request against the kiwi-ng repo: https://github.com/SUSE/kiwi/pull/376

Concerning the firmware stuff you are right with regards to graphics (kernel modesetting) and the radeon direct rendering engine, the firmware has to be in place at the first attempt to setup graphics, which is done in the kiwi initrd for e.g the plymouth stuff or when setting up the framebuffer console. If it failed at that stage the kernel disables modesetting and I don't know a way to get back to it later.

**Comment by schaefi** [comment]
The long list is a pain I agree but as long as all firmware is delivered in one big kernel-firmware package I see this problem to persist. kiwi already automatically removes all firmware where no driver exists anymore. See baseStripFirmware() method. Thus reducing the kernel drivers to the minimum needed will also reduce the amount of firmware files

**Comment by probonopd** [comment]
> Concerning the grub2 packages as part of the initrd, I have created a pull request against the kiwi-ng repo

Do you have a workaround that I could use for LEAP 42.2?

**Comment by schaefi** [comment]
I suggest you switch your buildservice build over to kiwi-ng. To make use of the latest version add the following repo to the image build:

```
<repository type="rpm-md" alias="kiwi-next-generation">
    <source path="obs://Virtualization:Appliances:Builder/openSUSE_Leap_42.2"/>
</repository>
```

doc hint: http://suse.github.io/kiwi/building/build_in_buildservice.html

**Comment by schaefi** [comment]
Let me know if that fits your project

**Comment by probonopd** [comment]
Looks like adding the repostitory to my .kiwi file has worked, but how can I check that my built image now is actually using kiwi-ng? Extracted the initrd with

```
sudo gzip -dc /livecd/boot/x86_64/loader/initrd  | cpio -i
linux@linux:~/initrd> grep COPY ./include
# COPYRIGHT     : (c) 2006 SUSE LINUX Products GmbH, Germany
```

Makes me wonder if I am actually using the latest one...

`./usr/lib/grub2/` stuff is still there in the initrd.

**Comment by probonopd** [comment]
When I add

```
<strip type="delete">
    <file name="/usr/lib/grub2/" />
</strip>
```

then I get

```
[ 1173s] Jun-24 15:20:49 <1> : Extracting initrd for boot graphics data lookup
[ 1173s] Jun-24 15:20:49 <1> : EXEC [mktemp -q -d /usr/src/packages/KIWI-iso/iso/boot-iso.XXXXXX]
[ 1173s] Jun-24 15:20:49 <1> : EXEC [gzip -9 -cd /usr/src/packages/KIWI-iso/iso/initrd-isoboot-suse-leap-42.1.x86_64-2.42.1.gz | (cd /usr/src/packages/KIWI-iso/iso/boot-iso.hEemH2 && cpio -di 2>&1)]
[ 1175s] Jun-24 15:20:51 <1> : Saving hybrid disk label in initrd: 0xd214c024...
[ 1175s] Jun-24 15:20:51 <1> : EXEC [mkdir -p /usr/src/packages/KIWI-iso/iso/boot-iso.hEemH2/boot/grub]
[ 1175s] Jun-24 15:20:51 <1> : EXEC [touch /usr/src/packages/KIWI-iso/iso/CD/boot/0xd214c024]
[ 1175s] Jun-24 15:20:51 <1> : EXEC [cd /usr/src/packages/KIWI-iso/iso/boot-iso.hEemH2 && find . | cpio --create --format=newc --quiet | gzip -9 -f > /usr/src/packages/KIWI-iso/iso/CD/boot/x86_64/loader/initrd]
[ 1238s] Jun-24 15:21:54 <3> : Couldn't find EFI grub2 data in: /usr/src/packages/KIWI-iso/iso/boot-iso.hEemH2/usr/lib/grub2/x86_64-efiJun-24 15:21:54 <3> : KIWI exited with error(s)
```

**Comment by schaefi** [comment]
That doesn't look like the next-ng builder was used in your project. You can check that via

```
osc buildlog images x86_64 | less

search for: python3-kiwi and get something like

[   45s] [416/417] cumulate python3-kiwi-9.7.4-28.1
[   92s] python3-kiwi-9.7.4-28.1    ...

later in the log you see the kiwi call with

/usr/bin/kiwi --compat -- --debug

The --compat indicates this is the new kiwi which is called, also the log output looks different, e.g

[  116s] [ INFO    ]: 03:52:24 | Loading XML description
```

If you need an example project try this one from our integration tests:

```
osc checkout Virtualization:Appliances:Images:Testing_x86/test-image-oem
```

**Comment by probonopd** [comment]
I get
```
[  146s] [360/376] cumulate kiwi-7.04.8-1.1
```
Your example is based on Tumbleweed while I am trying to use LEAP. Can you spot something that I am doing wrong? https://build.opensuse.org/package/show/home:probono:branches:KDE:Medias/openSUSE-Argon

**Comment by schaefi** [comment]
See my build branch based on yours here:

* https://build.opensuse.org/project/show/home:sax2:branches:home:probono:branches:KDE:Medias

I've done a few changes to the prj conf and the appliance description

**Comment by probonopd** [comment]
Thanks for your help @schaefi but now I get
```
[  197s] Jun-27 09:49:00 <3> : The required boot image description: 'isoboot/suse-leap42.2' for the selected build type: 'iso' does not exist. Jun-27 
```

**Comment by schaefi** [comment]
You are still building against kiwi v7 which doesn't have a 42.2 boot description. I guess that depends on the prio setup of your repos. I see your project defines repos in "osc meta prj" and in the .kiwi file. The buildservice combines them all together and does "something". I always recommend people who build images in the buildservice to keep all repos in one place, at best in the kiwi description and don't use any repo setup in the prj configuration. See "osc meta prj" of the branch I have created, there it builds

**Comment by probonopd** [comment]
Thanks for your help @schaefi please bear with me as I am new to OBS and so far only using the web interface. If I understand it correctly, I should remove one or both of the repositories from 
https://build.opensuse.org/project/meta/home:probono:branches:KDE:Medias
but when I try to save that I get:

> Unable to delete repository; following repositories depend on this project: 
> home:probono:branches:KDE:Medias/images

**Comment by schaefi** [comment]
ok, go to:

https://build.opensuse.org/project/meta/home:probono:branches:KDE:Medias

click on the Meta tab and make the xml look like this

```xml
<project name="home:probono:branches:KDE:Medias">
  <title>Branch project for package openSUSE-Argon</title>
  <description>Slimmed-down, customized version of openSUSE Argon (Leap with latest KDE)</description>
  <person userid="probono" role="maintainer"/>
  <repository name="images">
    <arch>x86_64</arch>
  </repository>
</project>
```

**Comment by schaefi** [comment]
Next install the osc package, if you are using the buildservice I strongly recommend to have this tool installed :)

Once installed and setup (credentials and such) call

```
osc linkdiff home:sax2:branches:home:probono:branches:KDE:Medias openSUSE-Argon
```

This shows you the changes I have done in my branch of your project. Apply those to your
project

**Comment by schaefi** [comment]
guess this one can be closed now, as you are on kiwi-ng now, let's discuss further issues on 
https://github.com/SUSE/kiwi

**Comment by probonopd** [comment]
Thank you @schaefi. I confirm it is working for me.
