### ISSUE TITLE
Installing dkms kernel module fails

### ISSUE THREAD

**Issue by probonopd** [openSUSE/kiwi#645]
Installing dkms kernel module fails. 
(I would like to install the anbox Android emulator on a kiwi Live ISO.)

If I understand it correctly, then in order for this to work, kiwi would need to:

1. Temporarily install the kernel headers
2. Compile the kernel modules with dkms and put in initramfs
3. Remove the kernel headers again so that they do not end up in the kiwi image

```
[  387s] (870/945) Installing: anbox-modules-dkms-0.0.1.git20170610-41.5.noarch [.......done]
[  387s] Additional rpm output:
[  387s] warning: /var/cache/kiwi/packages/usr_src_packages_SOURCES_repos_home:gasinvein:anbox_openSUSE_Leap_42.3/anbox-modules-dkms.rpm: Header V3 RSA/SHA256 Signature, key ID 61149b2f: NOKEY
[  387s] 
[  387s] Creating symlink /var/lib/dkms/anbox-ashmem/0.0.1.git20170610-41.5/source ->
[  387s]                  /usr/src/anbox-ashmem-0.0.1.git20170610-41.5
[  387s] 
[  387s] DKMS: add completed.
[  387s] Error! echo
[  387s] Your kernel headers for kernel 4.4.27-2-default cannot be found at
[  387s] /lib/modules/4.4.27-2-default/build or /lib/modules/4.4.27-2-default/source.
[  387s] 
[  387s] Creating symlink /var/lib/dkms/anbox-binder/0.0.1.git20170610-41.5/source ->
[  387s]                  /usr/src/anbox-binder-0.0.1.git20170610-41.5
[  387s] 
[  387s] DKMS: add completed.
[  387s] Error! echo
[  387s] Your kernel headers for kernel 4.4.27-2-default cannot be found at
[  387s] /lib/modules/4.4.27-2-default/build or /lib/modules/4.4.27-2-default/source.
```

**Comment by schaefi** [comment]
I would rather build a kernel module package (kmp) and just add that package to the list of packages in your image XML configuration as follows:

<package name="your-kmp-package" bootinclude="true"/>

We do not support source compilation and "auto-inclusion" of the result in the initrd during an image
build
