### ISSUE TITLE
Feature request: configure disk-start-sector from XML

### ISSUE THREAD

**Issue by matwey** [openSUSE/kiwi#662]
Hello,

There is kiwi command line command `--disk-start-sector` which is supposed to be used for switching first partition start sector value between old legacy 63-style and new default 2048.

However, it would be extremely useful to be able to specify this parameter as a part of XML kiwi receipt. Use case is the following. Modern non-x86 systems (i.e. aarch64 ones) uses custom vendor-defined layouts to store firmware at microSD cards, the same medium where OS is located. For instance, RockChip RK3328 requires different parts of the boot firmware to be stored at 64, 16384 and 24576 sectors from the media begin. This obviously overlaps with standard 2048 rule. If we were able to specify that first partition had to start at, say, 32768 sector in this particular case, then It would simplify JeOS building at OBS.

**Comment by davidcassany** [comment]
Hi @matwey, 

I'd like to point out that this kiwi version, the kiwi v7.x family, is in maintenance mode, no further development is done in this KIWI version besides patching reported bugs. The current KIWI development is taking place in [this](https://github.com/SUSE/kiwi) repository. You can check the docs of the current version [here](https://suse.github.io/kiwi). So any new feature should be developed over the current KIWI base.

I have included the issue into the current base code.

**Comment by matwey** [comment]
Current openSUSE:Factory JeOS infrastructure based on kiwi 7.x anyway.

**Comment by davidcassany** [comment]
@matwey, yes I am aware of it, at some point soon it needs to be upgraded to use more recent KIWI version. KIWI v7 is expected to be dropped in future opensuse and suse versions, thus improvements should take place in the next generation version of KIWI.

We work to make the transition as smooth as possible and I'd be glad to help in any way I can, I understand that if you have something already in place and working there is no reason for change, thats why kiwi v7 is still in place, but we do not plan any new feature in that code base.

**Comment by matwey** [comment]
Do you have any roadmap for Factory migration?
